<h1 style='color:blue;' align='center'>KFold Cross Validation Python Tutorial</h2>

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [3]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

<h3>Logistic Regression train-test-split score</h3>

In [40]:
get_score(LogisticRegression(solver='liblinear', multi_class='ovr'), X_train, X_test, y_train, y_test)

0.9098497495826378

<h3>SVM train-test-split score</h3>

In [5]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.987037037037037

<h3>Random Forest train-test-split score</h3>

In [6]:
get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test)

0.9722222222222222

<h2>KFold cross validation</h2>

In [8]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [10]:
for train_index, test_index in kf.split([1, 2, 3, 4, 5, 6, 7, 8, 9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


<h4>Basic Example</h4>

In [10]:
for train_index, test_index in kf.split([1, 2, 3, 4, 5, 6, 7, 8, 9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


<h4>Stratified K-Fold on digits data set</h4>

In [41]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in skf.split(digits.data, digits.target):
    X_train, X_test = digits.data[train_index], digits.data[test_index]
    y_train, y_test = digits.target[train_index], digits.target[test_index]

    scores_logistic.append(get_score(LogisticRegression(solver='liblinear', multi_class='ovr'), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))


In [33]:
scores_logistic

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [34]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [35]:
scores_rf

[0.9432387312186978, 0.9599332220367279, 0.9265442404006677]

<h2>cross_val_score function</h2> 

<p>cross_val_score uses stratified Kfold by default</p>

In [36]:
from sklearn.model_selection import cross_val_score

<h4>Logistic regression model performance using cross_val_score</h4>

In [39]:
cross_val_score(LogisticRegression(solver='liblinear', multi_class='ovr'), digits.data, digits.target, cv=3)

array([0.89482471, 0.95325543, 0.90984975])

<h4>svm model performance using cross_val_score</h4>

In [44]:
cross_val_score(SVC(), digits.data, digits.target, cv=3)

array([0.96494157, 0.97996661, 0.96494157])

<h4>Random forest model performance using cross_val_score</h4>

In [53]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target, cv=3)

array([0.91986644, 0.94156928, 0.92153589])

<h2>Parameter tuning using K fold cross validation</h2> 

In [58]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5), digits.data, digits.target, cv=10)
np.average(scores1)

0.8692644320297951

In [59]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20), digits.data, digits.target, cv=10)
np.average(scores2)

0.9398851644941029

In [60]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30), digits.data, digits.target, cv=10)
np.average(scores3)

0.9393234016139044

In [61]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target, cv=10)
np.average(scores4)

0.9443420235878335

In [62]:
scores5 = cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target, cv=10)
np.average(scores5)

0.9437926753569211