# Numpy Essentials

- NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing in Python.

In [1]:
import numpy as np

## 1D Arrays

In [2]:
my_list = [1, 2, 3, 4, 5]

arr = np.array(my_list)
arr

array([1, 2, 3, 4, 5])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.shape

(5,)

## 2D Arrays

In [5]:
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 1]
list3 = [2, 3, 4, 5, 9]

arr = np.array([list1, list2, list3])
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1],
       [2, 3, 4, 5, 9]])

In [6]:
arr.shape

(3, 5)

## Array Re-Shaping

In [8]:
arr.reshape(5, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 9]])

In [13]:
arr.shape

(3, 5)

## Indexing

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [15]:
arr[0]

1

In [16]:
arr[0:3]

array([1, 2, 3])

In [17]:
arr = np.array([list1, list2, list3])
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1],
       [2, 3, 4, 5, 9]])

In [21]:
arr[1:3, 1:4]

array([[7, 8, 9],
       [3, 4, 5]])

## 1 Line operations

In [22]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [23]:
arr < 6

array([ True,  True,  True,  True,  True, False])

In [24]:
arr * 2

array([ 2,  4,  6,  8, 10, 12])

In [25]:
arr / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

## Conditional Filtering

In [27]:
arr[arr < 5]

array([1, 2, 3, 4])

In [28]:
arr[arr > 3]

array([4, 5, 6])

## Pre-Initialization

In [29]:
np.arange(0, 10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [34]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [37]:
np.ones((4, 2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [36]:
np.random.rand(3, 3)

array([[0.61692703, 0.52583466, 0.33384396],
       [0.9739623 , 0.56737257, 0.824841  ],
       [0.45919223, 0.85294902, 0.74829459]])

## Random number generation

In [43]:
np.random.randint(0, 100, 3)

array([13, 93, 75])

In [48]:
np.random.random_sample((1, 3))

array([[0.89014342, 0.21673077, 0.6253118 ]])