# Pandas Data Frame and Data Series

In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.DataFrame(np.arange(0, 15).reshape(3, 5), index=['Row1', 'Row2', 'Row3'], columns=['Col1', 'Col2', 'Col3', 'Col4', 'Col5'])
df.head()

Col1  Col2  Col3  Col4  Col5
Row1     0     1     2     3     4
Row2     5     6     7     8     9
Row3    10    11    12    13    14

In [7]:
# df.to_csv('test.csv')

## Accessing elements

### Columns

In [32]:
df['Col1']

Row1     0
Row2     5
Row3    10
Name: Col1, dtype: int32

In [35]:
df[['Col1', 'Col2']]

Col1  Col2
Row1     0     1
Row2     5     6
Row3    10    11

### Rows

In [17]:
# 1. .loc 2. .iloc

df.loc['Row1']

Col1    0
Col2    1
Col3    2
Col4    3
Col5    4
Name: Row1, dtype: int32

In [36]:
df.loc[['Row1', 'Row2']]

Col1  Col2  Col3  Col4  Col5
Row1     0     1     2     3     4
Row2     5     6     7     8     9

In [9]:
type(df.loc['Row1'])

pandas.core.series.Series

### Slicing

In [11]:
df.iloc[0:2, 0:2]

Col1  Col2
Row1     0     1
Row2     5     6

In [12]:
type(df.iloc[0:2, 0:2])

pandas.core.frame.DataFrame

In [18]:
type(df.iloc[0:2, 0])

pandas.core.series.Series

## Convert Data Frames into arrays

In [19]:
df.values

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
df.loc['Row1'].values

array([0, 1, 2, 3, 4])

## Null value check

In [30]:
df.isnull().sum()

Col1    0
Col2    0
Col3    0
Col4    0
Col5    0
dtype: int64

## Category check

In [33]:
df['Col1'].value_counts()

Col1
0     1
5     1
10    1
Name: count, dtype: int64

In [34]:
df['Col2'].unique()

array([ 1,  6, 11])